on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: ./build.ps1
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: build/publish/*.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Build artifacts
          path: build/publish/*.zip
